-- 用途：订单统计 Excel 导出落库（python/excel/daily/order/订单统计-*.xlsx，表头在第 5 行）
-- 字符集：utf8mb4

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS sales_order_shipped (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  line_hash            CHAR(64) NOT NULL COMMENT '行内容稳定哈希（SHA-256 hex），用于去重与增量 UPSERT',

  platform             VARCHAR(64) NULL COMMENT '平台',
  shop_name_en         VARCHAR(128) NULL COMMENT '店铺英文名',
  shop_alias           VARCHAR(128) NULL COMMENT '店铺别名',
  platform_site        VARCHAR(64) NULL COMMENT '站点',
  warehouse_name       VARCHAR(255) NULL COMMENT '仓库',

  order_created_at     DATETIME NULL COMMENT '创建时间',
  pay_time             DATETIME NULL COMMENT '付款时间',
  ship_time            DATETIME NULL COMMENT '发货时间',
  audit_time           DATETIME NULL COMMENT '审核时间',

  order_sales_status   VARCHAR(64) NULL COMMENT '订单销售状态',
  order_type           VARCHAR(64) NULL COMMENT '订单类型',
  order_no             VARCHAR(128) NOT NULL COMMENT '订单号',
  ref_no               VARCHAR(128) NULL DEFAULT '' COMMENT '参考号',
  platform_sku_orig    VARCHAR(255) NULL COMMENT '原平台sku',
  platform_sku         VARCHAR(255) NULL COMMENT '平台sku',
  warehouse_sku        VARCHAR(128) NOT NULL COMMENT '仓库sku',
  warehouse_sku_qty    INT NULL COMMENT '仓库sku销量',
  product_name         VARCHAR(512) NULL COMMENT '产品名称',
  product_style        VARCHAR(512) NULL COMMENT '产品款式',
  brand                VARCHAR(128) NULL COMMENT '品牌',
  category_lv1         VARCHAR(128) NULL COMMENT '一级品类',
  category_lv2         VARCHAR(128) NULL COMMENT '二级品类',
  category_lv3         VARCHAR(128) NULL COMMENT '三级品类',
  product_sales_status VARCHAR(64) NULL COMMENT '产品销售状态',
  warehouse_order_no   VARCHAR(128) NULL COMMENT '仓库单号',
  provider_order_no    VARCHAR(128) NULL COMMENT '服务商单号',
  order_offline_type   VARCHAR(64) NULL COMMENT '订单下架类型',
  is_shipped           VARCHAR(16) NULL COMMENT '是否发货',
  is_after_sale        VARCHAR(16) NULL COMMENT '是否售后',
  tracking_no          VARCHAR(255) NULL COMMENT '跟踪单号',
  transaction_no       VARCHAR(255) NULL COMMENT '交易号',
  shipping_method      VARCHAR(255) NULL COMMENT '运输方式',
  product_weight       DECIMAL(18,6) NULL COMMENT '产品重量',
  ship_batch_no        VARCHAR(128) NULL COMMENT '发货批次号',

  pay_currency         VARCHAR(16) NULL COMMENT '订单付款币种',
  fx_rate_to_base      DECIMAL(18,8) NULL COMMENT '汇率（转本位币汇率）',

  unit_price_pay              DECIMAL(18,6) NULL COMMENT '销售单价（付款币种）',
  order_total_pay             DECIMAL(18,6) NULL COMMENT '订单总金额（付款币种）',
  order_goods_pay             DECIMAL(18,6) NULL COMMENT '订单商品金额（付款币种）',
  platform_shipping_pay       DECIMAL(18,6) NULL COMMENT '平台运费（付款币种）',
  payment_fee_pay             DECIMAL(18,6) NULL COMMENT '支付手续费（付款币种）',
  platform_fee_pay            DECIMAL(18,6) NULL COMMENT '平台手续费（付款币种）',
  fba_fee_pay                 DECIMAL(18,6) NULL COMMENT 'fba费用（付款币种）',
  platform_subsidy_pay        DECIMAL(18,6) NULL COMMENT '平台补贴费（付款币种）',
  tax_pay                     DECIMAL(18,6) NULL COMMENT '税费（付款币种）',
  other_fee_pay               DECIMAL(18,6) NULL COMMENT '其他费用（付款币种）',
  purchase_cost_pay           DECIMAL(18,6) NULL COMMENT '采购成本（付款币种）',
  purchase_shipping_pay       DECIMAL(18,6) NULL COMMENT '采购运费（付款币种）',
  purchase_tax_pay            DECIMAL(18,6) NULL COMMENT '采购税费（付款币种）',
  first_leg_shipping_pay      DECIMAL(18,6) NULL COMMENT '头程运费（付款币种）',
  first_leg_tax_pay           DECIMAL(18,6) NULL COMMENT '头程税费（付款币种）',
  packaging_fee_pay           DECIMAL(18,6) NULL COMMENT '包材费用（付款币种）',
  delivery_shipping_pay       DECIMAL(18,6) NULL COMMENT '派送运费（付款币种）',

  base_currency               VARCHAR(16) NULL COMMENT '本位币种（表中「币种」列）',
  unit_price_base             DECIMAL(18,6) NULL COMMENT '销售单价（本位币）',
  order_total_base            DECIMAL(18,6) NULL COMMENT '订单总金额（本位币）',
  order_goods_base            DECIMAL(18,6) NULL COMMENT '订单商品金额（本位币）',
  platform_shipping_base      DECIMAL(18,6) NULL COMMENT '平台运费（本位币）',
  payment_fee_base            DECIMAL(18,6) NULL COMMENT '支付手续费（本位币）',
  platform_fee_base           DECIMAL(18,6) NULL COMMENT '平台手续费（本位币）',
  fba_fee_base                DECIMAL(18,6) NULL COMMENT 'fba费用（本位币）',
  platform_subsidy_base       DECIMAL(18,6) NULL COMMENT '平台补贴费（本位币）',
  tax_base                    DECIMAL(18,6) NULL COMMENT '税费（本位币）',
  other_fee_base              DECIMAL(18,6) NULL COMMENT '其他费用（本位币）',
  purchase_cost_base          DECIMAL(18,6) NULL COMMENT '采购成本（本位币）',
  purchase_shipping_base      DECIMAL(18,6) NULL COMMENT '采购运费（本位币）',
  purchase_tax_base           DECIMAL(18,6) NULL COMMENT '采购税费（本位币）',
  first_leg_shipping_base     DECIMAL(18,6) NULL COMMENT '头程运费（本位币）',
  first_leg_tax_base          DECIMAL(18,6) NULL COMMENT '头程税费（本位币）',
  packaging_fee_base          DECIMAL(18,6) NULL COMMENT '包材费用（本位币）',
  delivery_shipping_base      DECIMAL(18,6) NULL COMMENT '派送运费（本位币）',
  total_fee_base              DECIMAL(18,6) NULL COMMENT '总费用（本位币）',
  total_cost_base             DECIMAL(18,6) NULL COMMENT '总成本（本位币）',
  gross_profit_base           DECIMAL(18,6) NULL COMMENT '毛利（本位币）',
  gross_margin_rate           DECIMAL(10,6) NULL COMMENT '毛利率（小数，如 0.225 表示 22.5%）',

  item_id              VARCHAR(128) NULL COMMENT 'ITEM_ID',
  asin                 VARCHAR(64) NULL COMMENT 'ASIN',
  orig_sales_order_no  VARCHAR(128) NULL COMMENT '原销售订单号',
  sales_owner          VARCHAR(128) NULL COMMENT '销售负责人',
  purchase_owner       VARCHAR(128) NULL COMMENT '采购负责人',
  dev_owner            VARCHAR(128) NULL COMMENT '开发负责人',
  sub_sales            VARCHAR(128) NULL COMMENT '附属销售员',
  platform_sku_owner   VARCHAR(128) NULL COMMENT '平台sku负责人',
  shop_owner           VARCHAR(128) NULL COMMENT '店铺负责人',

  buyer_id             VARCHAR(128) NULL COMMENT '买家ID',
  buyer_email          VARCHAR(255) NULL COMMENT '买家邮箱',
  phone                VARCHAR(128) NULL COMMENT '电话',
  buyer_name           VARCHAR(255) NULL COMMENT '买家姓名',
  consignee            VARCHAR(255) NULL COMMENT '收件人',
  country              VARCHAR(128) NULL COMMENT '国家',
  state                VARCHAR(128) NULL COMMENT '州/省',
  city                 VARCHAR(128) NULL COMMENT '城市',
  address_line         VARCHAR(1024) NULL COMMENT '联系地址',
  postal_code          VARCHAR(64) NULL COMMENT '邮编',
  sales_order_no       VARCHAR(128) NULL COMMENT '销售订单号',
  cs_remark            VARCHAR(2048) NULL COMMENT '客服备注',
  system_remark        VARCHAR(2048) NULL COMMENT '系统备注',
  finance_remark       VARCHAR(2048) NULL COMMENT '财务备注',
  shopify_pay_method   VARCHAR(128) NULL COMMENT 'shopify支付方式',
  shopify_pay_txn_no   VARCHAR(255) NULL COMMENT 'shopify支付交易号',
  offline_fee_summary  DECIMAL(18,6) NULL COMMENT '线下费用汇总',
  profit_calc_node     VARCHAR(24) NULL COMMENT '利润聚合标记：NULL/空=尚未纳入 sales_order_sku_profit 批次；非空=已由 run_order_sku_profit 写入该批次节点名或短批次号（同键多行应一致更新）',
  source_type          VARCHAR(24) NULL COMMENT '来源类型：Excel/API',

  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '写入时间',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',

  PRIMARY KEY (id),
  UNIQUE KEY uk_order_line_hash (line_hash),
  -- 说明：多列业务唯一键在 utf8mb4 下易超过 InnoDB 索引最大 3072 字节（本表原组合约 3580B），
  --       业务去重请依赖 line_hash；查询用下方单列/少列索引即可。
  KEY idx_sol_order_no (order_no),
  KEY idx_sol_pay_time (pay_time),
  KEY idx_sol_platform (platform),
  KEY idx_sol_shop (shop_alias),
  KEY idx_sol_warehouse_sku (warehouse_sku)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='订单明细-按行落库';
