-- ========================================
-- 表：amz_transaction
-- 数据库：rpa-report
-- 导出时间：2026-06-12 14:17:41
-- 来源：局域网数据库 172.18.188.18:3309
-- ========================================
SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;
USE rpa-report;

DROP TABLE IF EXISTS amz_transaction;
CREATE TABLE `amz_transaction` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `line_hash` char(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '行内容稳定哈希（SHA-256 hex），用于去重与增量 UPSERT',
  `source_kind` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '来源分类：released=已发放订单 deferred=已推迟订单',
  `period_label` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '期间（Excel「期间」如 2026-05）',
  `report_row_at` datetime DEFAULT NULL COMMENT '报表原日期',
  `shop_name` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '店铺名称',
  `site_code` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '站点',
  `currency` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '币种',
  `payout_reconcile_status` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '划款账单对账状态',
  `payout_at` datetime DEFAULT NULL COMMENT '划款时间',
  `settlement_start_at` datetime DEFAULT NULL COMMENT '结算时间-开始',
  `settlement_end_at` datetime DEFAULT NULL COMMENT '结算时间-结束',
  `settlement_at` datetime DEFAULT NULL COMMENT '结算时间',
  `shipped_at` datetime DEFAULT NULL COMMENT '发货时间',
  `ship_warehouse` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '发货仓库',
  `group_id` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Amazon group id（结算分组）',
  `transaction_type` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'type：order/refund/serviceFee 等',
  `amazon_order_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'order id',
  `original_sales_order_no` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '原销售订单号',
  `merchant_order_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'merchantOrderId',
  `fulfillment_channel` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '配送方式 FBA/FBM 等',
  `seller_sku` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'seller sku',
  `platform_sku` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '标准化 SKU（由 seller_sku 清洗得到，用于与订单统计对齐）',
  `child_asin` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '子ASIN',
  `parent_asin` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '父ASIN',
  `warehouse_sku` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'warehouse sku',
  `line_description` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'description',
  `quantity` decimal(18,4) DEFAULT NULL COMMENT '数量',
  `marketplace` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'marketplace（如 Amazon.de）',
  `product_sales` decimal(18,6) DEFAULT NULL COMMENT 'product sales',
  `product_sales_tax` decimal(18,6) DEFAULT NULL COMMENT 'product sales tax',
  `shipping_credits` decimal(18,6) DEFAULT NULL COMMENT 'shipping credits',
  `shipping_credits_tax` decimal(18,6) DEFAULT NULL COMMENT 'shipping credits tax',
  `gift_wrap_credits` decimal(18,6) DEFAULT NULL COMMENT 'gift wrap credits',
  `gift_wrap_credits_tax` decimal(18,6) DEFAULT NULL COMMENT 'gift wrap credits tax',
  `regulatory_fee` decimal(18,6) DEFAULT NULL COMMENT 'regulatory fee',
  `promotional_rebates` decimal(18,6) DEFAULT NULL COMMENT 'promotional rebates',
  `promotional_rebates_tax` decimal(18,6) DEFAULT NULL COMMENT 'promotional rebates tax',
  `marketplace_withheld_tax` decimal(18,6) DEFAULT NULL COMMENT 'marketplace withheld tax',
  `sales_tax_collected` decimal(18,6) DEFAULT NULL COMMENT 'sales tax collected',
  `low_value_goods` decimal(18,6) DEFAULT NULL COMMENT 'low value goods',
  `amazon_point_costs` decimal(18,6) DEFAULT NULL COMMENT 'amazon point costs',
  `selling_fees` decimal(18,6) DEFAULT NULL COMMENT 'selling fees',
  `fba_fees` decimal(18,6) DEFAULT NULL COMMENT 'fba fees',
  `other_transaction_fees` decimal(18,6) DEFAULT NULL COMMENT 'other transaction fees',
  `other_amount` decimal(18,6) DEFAULT NULL COMMENT 'other',
  `total_amount` decimal(18,6) DEFAULT NULL COMMENT 'total',
  `purchase_cost` decimal(18,6) DEFAULT NULL COMMENT '采购成本',
  `purchase_shipping` decimal(18,6) DEFAULT NULL COMMENT '采购运费',
  `purchase_tax` decimal(18,6) DEFAULT NULL COMMENT '采购税费',
  `first_leg_shipping` decimal(18,6) DEFAULT NULL COMMENT '头程运费',
  `first_leg_tax` decimal(18,6) DEFAULT NULL COMMENT '头程税费',
  `fx_rate_cny` decimal(18,8) DEFAULT NULL COMMENT '转人民币汇率',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '写入时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_amz_txn_line_hash` (`line_hash`),
  KEY `idx_amz_txn_order` (`amazon_order_id`),
  KEY `idx_amz_txn_order_platform_sku` (`amazon_order_id`,`platform_sku`),
  KEY `idx_amz_txn_shop_period` (`shop_name`,`period_label`),
  KEY `idx_amz_txn_settlement` (`settlement_at`),
  KEY `idx_amz_txn_group` (`group_id`),
  KEY `idx_amz_txn_type` (`transaction_type`)
) ENGINE=InnoDB AUTO_INCREMENT=13245 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Amazon-transaction交易明细';
