-- ========================================
-- 表：month_orders_shipped
-- 数据库：rpa-report
-- 导出时间：2026-06-12 14:17:41
-- 来源：局域网数据库 172.18.188.18:3309
-- ========================================
SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;
USE rpa-report;

DROP TABLE IF EXISTS month_orders_shipped;
CREATE TABLE `month_orders_shipped` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `line_hash` char(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '行内容稳定哈希（月报含 warehouse_sku，与日报 hash 语义不同）',
  `stat_month` char(7) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '统计月 YYYY-MM',
  `report_date` date NOT NULL COMMENT '报表日期（一般为当月最后一天）',
  `import_batch` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '导入文件内容 hash，便于按批次核对',
  `source_type` varchar(24) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '来源类型：Excel/API',
  `platform` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '平台',
  `shop_name_en` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '店铺英文名',
  `shop_alias` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '店铺别名',
  `platform_site` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '站点',
  `warehouse_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '仓库',
  `order_created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `pay_time` datetime DEFAULT NULL COMMENT '付款时间',
  `ship_time` datetime DEFAULT NULL COMMENT '发货时间',
  `audit_time` datetime DEFAULT NULL COMMENT '审核时间',
  `order_sales_status` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '订单销售状态',
  `order_type` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '订单类型',
  `order_no` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '订单号',
  `ref_no` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '参考号',
  `platform_sku_orig` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '原平台sku',
  `platform_sku` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '平台sku',
  `warehouse_sku` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '仓库sku',
  `warehouse_sku_qty` int DEFAULT NULL COMMENT '仓库sku销量',
  `product_name` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '产品名称',
  `product_style` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '产品款式',
  `brand` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '品牌',
  `category_lv1` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '一级品类',
  `category_lv2` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '二级品类',
  `category_lv3` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '三级品类',
  `product_sales_status` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '产品销售状态',
  `warehouse_order_no` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '仓库单号',
  `provider_order_no` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '服务商单号',
  `order_offline_type` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '订单下架类型',
  `is_shipped` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '是否发货',
  `is_after_sale` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '是否售后',
  `tracking_no` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '跟踪单号',
  `transaction_no` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '交易号',
  `shipping_method` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '运输方式',
  `product_weight` decimal(18,6) DEFAULT NULL COMMENT '产品重量',
  `ship_batch_no` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '发货批次号',
  `pay_currency` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '订单付款币种',
  `fx_rate_to_base` decimal(18,8) DEFAULT NULL COMMENT '汇率（转本位币汇率）',
  `unit_price_pay` decimal(18,6) DEFAULT NULL COMMENT '销售单价（付款币种）',
  `order_total_pay` decimal(18,6) DEFAULT NULL COMMENT '订单总金额（付款币种）',
  `order_goods_pay` decimal(18,6) DEFAULT NULL COMMENT '订单商品金额（付款币种）',
  `platform_shipping_pay` decimal(18,6) DEFAULT NULL COMMENT '平台运费（付款币种）',
  `payment_fee_pay` decimal(18,6) DEFAULT NULL COMMENT '支付手续费（付款币种）',
  `platform_fee_pay` decimal(18,6) DEFAULT NULL COMMENT '平台手续费（付款币种）',
  `fba_fee_pay` decimal(18,6) DEFAULT NULL COMMENT 'fba费用（付款币种）',
  `platform_subsidy_pay` decimal(18,6) DEFAULT NULL COMMENT '平台补贴费（付款币种）',
  `tax_pay` decimal(18,6) DEFAULT NULL COMMENT '税费（付款币种）',
  `other_fee_pay` decimal(18,6) DEFAULT NULL COMMENT '其他费用（付款币种）',
  `purchase_cost_pay` decimal(18,6) DEFAULT NULL COMMENT '采购成本（付款币种）',
  `purchase_shipping_pay` decimal(18,6) DEFAULT NULL COMMENT '采购运费（付款币种）',
  `purchase_tax_pay` decimal(18,6) DEFAULT NULL COMMENT '采购税费（付款币种）',
  `first_leg_shipping_pay` decimal(18,6) DEFAULT NULL COMMENT '头程运费（付款币种）',
  `first_leg_tax_pay` decimal(18,6) DEFAULT NULL COMMENT '头程税费（付款币种）',
  `packaging_fee_pay` decimal(18,6) DEFAULT NULL COMMENT '包材费用（付款币种）',
  `delivery_shipping_pay` decimal(18,6) DEFAULT NULL COMMENT '派送运费（付款币种）',
  `base_currency` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '本位币种',
  `unit_price_base` decimal(18,6) DEFAULT NULL COMMENT '销售单价（本位币）',
  `order_total_base` decimal(18,6) DEFAULT NULL COMMENT '订单总金额（本位币）',
  `order_goods_base` decimal(18,6) DEFAULT NULL COMMENT '订单商品金额（本位币）',
  `platform_shipping_base` decimal(18,6) DEFAULT NULL COMMENT '平台运费（本位币）',
  `payment_fee_base` decimal(18,6) DEFAULT NULL COMMENT '支付手续费（本位币）',
  `platform_fee_base` decimal(18,6) DEFAULT NULL COMMENT '平台手续费（本位币）',
  `fba_fee_base` decimal(18,6) DEFAULT NULL COMMENT 'fba费用（本位币）',
  `platform_subsidy_base` decimal(18,6) DEFAULT NULL COMMENT '平台补贴费（本位币）',
  `tax_base` decimal(18,6) DEFAULT NULL COMMENT '税费（本位币）',
  `other_fee_base` decimal(18,6) DEFAULT NULL COMMENT '其他费用（本位币）',
  `purchase_cost_base` decimal(18,6) DEFAULT NULL COMMENT '采购成本（本位币）',
  `purchase_shipping_base` decimal(18,6) DEFAULT NULL COMMENT '采购运费（本位币）',
  `purchase_tax_base` decimal(18,6) DEFAULT NULL COMMENT '采购税费（本位币）',
  `first_leg_shipping_base` decimal(18,6) DEFAULT NULL COMMENT '头程运费（本位币）',
  `first_leg_tax_base` decimal(18,6) DEFAULT NULL COMMENT '头程税费（本位币）',
  `packaging_fee_base` decimal(18,6) DEFAULT NULL COMMENT '包材费用（本位币）',
  `delivery_shipping_base` decimal(18,6) DEFAULT NULL COMMENT '派送运费（本位币）',
  `total_fee_base` decimal(18,6) DEFAULT NULL COMMENT '总费用（本位币）',
  `total_cost_base` decimal(18,6) DEFAULT NULL COMMENT '总成本（本位币）',
  `gross_profit_base` decimal(18,6) DEFAULT NULL COMMENT '毛利（本位币）',
  `gross_margin_rate` decimal(10,6) DEFAULT NULL COMMENT '毛利率',
  `item_id` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'ITEM_ID',
  `asin` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'ASIN',
  `orig_sales_order_no` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '原销售订单号',
  `sales_owner` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '销售负责人',
  `purchase_owner` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '采购负责人',
  `dev_owner` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '开发负责人',
  `sub_sales` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '附属销售员',
  `platform_sku_owner` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '平台sku负责人',
  `shop_owner` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '店铺负责人',
  `buyer_id` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '买家ID',
  `buyer_email` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '买家邮箱',
  `phone` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '电话',
  `buyer_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '买家姓名',
  `consignee` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '收件人',
  `country` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '国家',
  `state` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '州/省',
  `city` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '城市',
  `address_line` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '联系地址',
  `postal_code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '邮编',
  `sales_order_no` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '销售订单号',
  `cs_remark` varchar(2048) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '客服备注',
  `system_remark` varchar(2048) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '系统备注',
  `finance_remark` varchar(2048) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '财务备注',
  `shopify_pay_method` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'shopify支付方式',
  `shopify_pay_txn_no` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'shopify支付交易号',
  `offline_fee_summary` decimal(18,6) DEFAULT NULL COMMENT '线下费用汇总',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '写入时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_month_line` (`stat_month`,`line_hash`),
  KEY `idx_mos_stat_month` (`stat_month`),
  KEY `idx_mos_import_batch` (`import_batch`),
  KEY `idx_mos_report_date` (`report_date`),
  KEY `idx_mos_order_no` (`order_no`),
  KEY `idx_mos_pay_time` (`pay_time`),
  KEY `idx_mos_warehouse_sku` (`warehouse_sku`)
) ENGINE=InnoDB AUTO_INCREMENT=73401 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='月报订单明细';
