-- ========================================
-- 表：month_orders_refund
-- 数据库：rpa-report
-- 导出时间：2026-06-12 14:17:41
-- 来源：局域网数据库 172.18.188.18:3309
-- ========================================
SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;
USE rpa-report;

DROP TABLE IF EXISTS month_orders_refund;
CREATE TABLE `month_orders_refund` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `line_hash` char(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '行内容稳定哈希（月报语义，可与日报 hash 不同）',
  `stat_month` char(7) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '统计月 YYYY-MM',
  `report_date` date NOT NULL COMMENT '报表日期（一般为当月最后一天）',
  `import_batch` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '导入文件内容 hash，便于按批次核对',
  `source_type` varchar(24) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '来源类型：Excel/API',
  `platform` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '平台',
  `shop_alias` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '店铺别名',
  `shop_name_en` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '店铺英文名',
  `platform_site` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '站点',
  `warehouse_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '仓库名称',
  `order_dest_country` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '订单目的国家',
  `rma_created_at` datetime DEFAULT NULL COMMENT 'RMA创建时间',
  `rma_audit_at` datetime DEFAULT NULL COMMENT 'RMA审核时间',
  `rma_refund_at` datetime DEFAULT NULL COMMENT 'RMA退款时间',
  `orig_order_paid_at` datetime DEFAULT NULL COMMENT '原订单付款时间',
  `refund_orig_order_no` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '退款原订单号',
  `refund_orig_ref_no` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '退款原订单参考号',
  `refund_orig_track_no` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '退款原订单跟踪号',
  `paypal_refund_txn_no` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'PayPal退款交易号',
  `refund_type` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '退款类型',
  `shipping_method` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '运输方式',
  `shipping_method_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '运输方式名称',
  `refund_status` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '退款状态',
  `refund_method` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '退款方式',
  `rma_product_sku` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'RMA产品',
  `rma_product_qty` decimal(18,6) DEFAULT NULL COMMENT 'RMA产品数量',
  `currency_code` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '币种',
  `product_name` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '产品名称',
  `category_lv1` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '一级品类',
  `category_lv2` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '二级品类',
  `category_lv3` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '三级品类',
  `product_style` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '产品款式',
  `refund_amount` decimal(18,6) DEFAULT NULL COMMENT '退款金额',
  `refund_reason` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '退款原因',
  `platform_refund_reason` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '平台退款原因',
  `created_by` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创建人',
  `refund_remark` varchar(2048) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '退款备注',
  `finance_remark` varchar(2048) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '财务备注',
  `default_buyer_acct` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '产品默认采购员账号',
  `default_buyer_name` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '产品默认采购员',
  `sales_owner_acct` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '销售负责人账号',
  `sales_owner` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '销售负责人',
  `dev_owner_acct` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '开发负责人账号',
  `dev_owner` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '开发负责人',
  `ops_owner` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '运营负责人',
  `product_issue_type` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '产品问题类型',
  `issue_category` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '问题分类',
  `product_issue` varchar(2048) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '产品问题',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '写入时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_month_refund_line` (`stat_month`,`line_hash`),
  KEY `idx_mor_stat_month` (`stat_month`),
  KEY `idx_mor_import_batch` (`import_batch`),
  KEY `idx_mor_report_date` (`report_date`),
  KEY `idx_mor_refund_orig` (`refund_orig_order_no`),
  KEY `idx_mor_refund_at` (`rma_refund_at`),
  KEY `idx_mor_platform` (`platform`)
) ENGINE=InnoDB AUTO_INCREMENT=2107 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='月报 RMA 退款明细';
