-- ========================================
-- 表：product_sku_pricing
-- 数据库：rpa-report
-- 导出时间：2026-06-12 14:17:41
-- 来源：局域网数据库 172.18.188.18:3309
-- ========================================
SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;
USE rpa-report;

DROP TABLE IF EXISTS product_sku_pricing;
CREATE TABLE `product_sku_pricing` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `line_hash` char(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '行内容稳定哈希（SHA-256 hex），变更检测用',
  `product_sku` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '产品SKU（业务唯一键，Excel第2列）',
  `cost_price_cny` decimal(18,6) DEFAULT NULL COMMENT '成本价（人民币）',
  `unit_weight_g` decimal(12,2) DEFAULT NULL COMMENT '单件重量（g）',
  `region_spec` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '规格/适用地区（欧规/美规/英规/日本/澳规/通用/常规/配件/国内配置）',
  `inner_box_l_cm` decimal(10,2) DEFAULT NULL COMMENT '内箱长（cm）',
  `inner_box_w_cm` decimal(10,2) DEFAULT NULL COMMENT '内箱宽（cm）',
  `inner_box_h_cm` decimal(10,2) DEFAULT NULL COMMENT '内箱高（cm）',
  `outer_box_l_cm` decimal(10,2) DEFAULT NULL COMMENT '外箱长（cm）',
  `outer_box_w_cm` decimal(10,2) DEFAULT NULL COMMENT '外箱宽（cm）',
  `outer_box_h_cm` decimal(10,2) DEFAULT NULL COMMENT '外箱高（cm）',
  `carton_qty` int unsigned DEFAULT NULL COMMENT '箱规（每外箱产品数量，个）',
  `carton_gross_g` decimal(12,2) DEFAULT NULL COMMENT '箱规毛重（g）',
  `first_leg_eu_au_cny` decimal(18,6) DEFAULT NULL COMMENT '头程运费 EU/AU（RMB/件）',
  `first_leg_us_cny` decimal(18,6) DEFAULT NULL COMMENT '头程运费 US（RMB/件）',
  `first_leg_ca_cny` decimal(18,6) DEFAULT NULL COMMENT '头程运费 CA（RMB/件）',
  `first_leg_jp_cny` decimal(18,6) DEFAULT NULL COMMENT '头程运费 JP（RMB/件）',
  `first_leg_uk_cny` decimal(18,6) DEFAULT NULL COMMENT '头程运费 UK（RMB/件）',
  `duty_eu_cny` decimal(18,6) DEFAULT NULL COMMENT '关税含税 EU（RMB/件）',
  `duty_us_cny` decimal(18,6) DEFAULT NULL COMMENT '关税含税 US（RMB/件，通常为0）',
  `duty_ca_au_cny` decimal(18,6) DEFAULT NULL COMMENT '关税含税 CA/AU（RMB/件）',
  `duty_jp_cny` decimal(18,6) DEFAULT NULL COMMENT '关税含税 JP（RMB/件）',
  `duty_uk_cny` decimal(18,6) DEFAULT NULL COMMENT '关税含税 UK（RMB/件）',
  `duty_eu_notax_cny` decimal(18,6) DEFAULT NULL COMMENT '关税不含税 EU（RMB/件）',
  `duty_us_notax_cny` decimal(18,6) DEFAULT NULL COMMENT '关税不含税 US（RMB/件）',
  `duty_ca_au_notax_cny` decimal(18,6) DEFAULT NULL COMMENT '关税不含税 CA/AU（RMB/件）',
  `duty_jp_notax_cny` decimal(18,6) DEFAULT NULL COMMENT '关税不含税 JP（RMB/件）',
  `duty_uk_notax_cny` decimal(18,6) DEFAULT NULL COMMENT '关税不含税 UK（RMB/件）',
  `purchase_price_orig_cny` decimal(18,6) DEFAULT NULL COMMENT '原始采购价（人民币）',
  `purchase_price_default_cny` decimal(18,6) DEFAULT NULL COMMENT '默认采购价（当前生效价，人民币）',
  `purchase_price_may_cny` decimal(18,6) DEFAULT NULL COMMENT '5月采购价（人民币）',
  `purchase_price_jun_cny` decimal(18,6) DEFAULT NULL COMMENT '6月采购价（人民币）',
  `purchase_price_sep_cny` decimal(18,6) DEFAULT NULL COMMENT '9月采购价（人民币）',
  `commission_pct_regular` decimal(8,4) DEFAULT NULL COMMENT '代运营佣金点-常规',
  `commission_pct_may_de` decimal(8,4) DEFAULT NULL COMMENT '5月佣金点-DE站',
  `commission_pct_may_non_de` decimal(8,4) DEFAULT NULL COMMENT '5月佣金点-非DE站',
  `commission_pct_jun_de` decimal(8,4) DEFAULT NULL COMMENT '6月佣金点-DE站',
  `commission_pct_jun_non_de` decimal(8,4) DEFAULT NULL COMMENT '6月佣金点-非DE站',
  `commission_pct_sep_de` decimal(8,4) DEFAULT NULL COMMENT '9月佣金点-DE站',
  `commission_pct_sep_non_de` decimal(8,4) DEFAULT NULL COMMENT '9月佣金点-非DE站',
  `price_modified_cny` decimal(18,6) DEFAULT NULL COMMENT '修改后单价（人民币，有调价记录时填写）',
  `price_modified_date` date DEFAULT NULL COMMENT '预计修改生效时间',
  `supplier_code` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '供应商代码（如 F003、F005）',
  `supplier_name` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '供应商简称（如 金铭、慕家）',
  `supplier_full_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '供应商全称（含代码，如 F003[江门市金铭卫浴有限公司]）',
  `category` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '品类（如 面盆水龙头、淋浴、厨房水龙头、售后配件）',
  `ops_mode` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '运营模式（代运营 / 自运营）',
  `sales_status` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '产品销售状态（正常销售/清仓/重点产品/新品/仅售后配件/正常售完下架）',
  `product_name` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '产品名称（中文简称）',
  `dev_owner` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '开发负责人姓名',
  `product_dev_date` date DEFAULT NULL COMMENT '产品开发时间',
  `product_launch_date` date DEFAULT NULL COMMENT '产品上架时间',
  `source_type` varchar(24) COLLATE utf8mb4_unicode_ci DEFAULT 'Excel' COMMENT '来源类型：Excel/API',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '写入时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_psp_product_sku` (`product_sku`),
  KEY `idx_psp_supplier_code` (`supplier_code`),
  KEY `idx_psp_category` (`category`),
  KEY `idx_psp_ops_mode` (`ops_mode`),
  KEY `idx_psp_sales_status` (`sales_status`),
  KEY `idx_psp_region_spec` (`region_spec`)
) ENGINE=InnoDB AUTO_INCREMENT=5204 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='产品SKU定价与成本主数据表（来源：BTH全部SKU明细 → 基础数据维护）';
