-- ========================================
-- 表：sales_order_returned
-- 数据库：rpa-report
-- 导出时间：2026-06-12 14:17:41
-- 来源：局域网数据库 172.18.188.18:3309
-- ========================================
SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;
USE rpa-report;

DROP TABLE IF EXISTS sales_order_returned;
CREATE TABLE `sales_order_returned` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `line_hash` char(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '行内容稳定哈希（SHA-256 hex），用于去重与增量 UPSERT',
  `platform` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '平台',
  `shop_name_en` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '店铺英文名',
  `shop_alias` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '店铺别名',
  `platform_site` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '站点',
  `market_region` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '区域站点',
  `market_code` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '销售区域',
  `warehouse_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '仓库名称',
  `warehouse_code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '仓库代码（与仓租明细 Warehouse Code 一致时可填）',
  `return_doc_no` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '退件单号/WMS退件单号',
  `receiving_no` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '入库单/收货单号（可与仓租明细 Receiving 对齐）',
  `rma_no` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'RMA编号（若有，可与 sales_order_refund 业务关联）',
  `orig_order_no` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '原销售订单号（平台订单号）',
  `orig_ref_no` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '原订单参考号',
  `orig_sales_order_no` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '原销售订单号（业务侧）',
  `orig_tracking_no` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '原 outbound 跟踪号（可选）',
  `return_type` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '退件类型：买家退货/拒收/截单退回/换货退回等',
  `return_status` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '退件状态：待收货/已收货/已上架/质检不通过等',
  `disposition` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '处置：重新上架/报废/待判/转库存等',
  `platform_sku` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '平台 SKU',
  `warehouse_sku` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '仓库 SKU（如 900008-XXX）',
  `product_sku` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '产品 SKU：导入时取 warehouse_sku 去掉前缀 900008- 后的后缀',
  `product_name` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '产品名称',
  `return_qty` decimal(18,6) NOT NULL COMMENT '退件数量（支持小数场景时与源表一致）',
  `received_qty` decimal(18,6) DEFAULT NULL COMMENT '实收数量（签收/清点）',
  `putaway_qty` decimal(18,6) DEFAULT NULL COMMENT '已上架数量',
  `return_tracking_no` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '退件物流跟踪号',
  `carrier` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '承运商/物流商',
  `shipping_method` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '运输方式',
  `apply_at` datetime DEFAULT NULL COMMENT '退件申请时间',
  `buyer_ship_at` datetime DEFAULT NULL COMMENT '买家寄出时间',
  `received_at` datetime DEFAULT NULL COMMENT '仓库签收时间',
  `putaway_at` datetime DEFAULT NULL COMMENT '上架完成时间（与仓租 Putaway Date 语义一致）',
  `inspected_at` datetime DEFAULT NULL COMMENT '质检完成时间',
  `length_cm` decimal(18,6) DEFAULT NULL COMMENT '长 cm',
  `width_cm` decimal(18,6) DEFAULT NULL COMMENT '宽 cm',
  `height_cm` decimal(18,6) DEFAULT NULL COMMENT '高 cm',
  `volume_m3` decimal(18,6) DEFAULT NULL COMMENT '体积 m³',
  `weight_kg` decimal(18,6) DEFAULT NULL COMMENT '重量 kg',
  `currency_code` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '币种（处理费/货值等）',
  `handling_fee` decimal(18,6) DEFAULT NULL COMMENT '退件处理费',
  `declared_value` decimal(18,6) DEFAULT NULL COMMENT '申报/核定货值（可选）',
  `sales_owner` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '销售负责人',
  `platform_sku_owner` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '平台 SKU 负责人',
  `cs_remark` varchar(2048) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '客服备注',
  `warehouse_remark` varchar(2048) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '仓库备注',
  `profit_calc_node` varchar(24) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '利润/聚合批次标记（与 shipped/refund 同风格，可选）',
  `report_date` date DEFAULT NULL COMMENT '报表日期',
  `report_hash` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '报表哈希',
  `source_type` varchar(24) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '来源类型：Excel/API',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '写入时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_return_line_hash` (`line_hash`),
  KEY `idx_ret_orig_order` (`orig_order_no`),
  KEY `idx_ret_received` (`received_at`),
  KEY `idx_ret_warehouse_sku` (`warehouse_sku`),
  KEY `idx_ret_product_sku` (`product_sku`),
  KEY `idx_ret_return_doc` (`return_doc_no`),
  KEY `idx_ret_receiving` (`receiving_no`),
  KEY `idx_ret_platform` (`platform`),
  KEY `idx_ret_report_date` (`report_date`),
  KEY `idx_ret_report_hash` (`report_hash`)
) ENGINE=InnoDB AUTO_INCREMENT=541 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='销售退件/二次上架明细';
